# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RepoMonitor < Formula
  desc "Monitor open PRs and active CIs for a GitHub org from the terminal"
  homepage "https://github.com/zarvhq/repo-monitor"
  version "0.1.1"
  license "MIT"

  depends_on "gh"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zarvhq/homebrew-tap/releases/download/v0.1.1/repo-monitor_darwin_amd64.tar.gz"
      sha256 "fae0693191b5178f4551d0ff20100eb3b7d2e0abc4bc606bd1decbaa0fe01667"

      define_method(:install) do
        bin.install "repo-monitor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zarvhq/homebrew-tap/releases/download/v0.1.1/repo-monitor_darwin_arm64.tar.gz"
      sha256 "00b28e4a7f513568d2136c20d18c2c6611cea1616a1c37aab94095a7cba8b78f"

      define_method(:install) do
        bin.install "repo-monitor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarvhq/homebrew-tap/releases/download/v0.1.1/repo-monitor_linux_amd64.tar.gz"
      sha256 "01841488e0f2b0f5163bfc03d7553b177511cefc24931b270baf5ec8de7add37"
      define_method(:install) do
        bin.install "repo-monitor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarvhq/homebrew-tap/releases/download/v0.1.1/repo-monitor_linux_arm64.tar.gz"
      sha256 "5916baa4a7190f83741aac8a0a68964de3c79e434dd50a27db415766dcaf4f57"
      define_method(:install) do
        bin.install "repo-monitor"
      end
    end
  end

  test do
    system "#{bin}/repo-monitor", "--version"
  end
end
